language: php
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.0
    env: L5_VER=4
  - php: 7.0
    env: L5_VER=5
  - php: 7.1
    env: L5_VER=4
  - php: 7.1
    env: L5_VER=5
  - php: 7.1
    env: L5_VER=6
  - php: 7.1
    env: L5_VER=7
  - php: 7.2
    env: L5_VER=4
  - php: 7.2
    env: L5_VER=5
  - php: 7.2
    env: L5_VER=6
  - php: 7.2
    env: L5_VER=7
script:
- vendor/bin/phpunit -c phpunit.xml
before_install:
- composer require "illuminate/support:5.${L5_VER}.*" --no-update -v
- composer require "illuminate/console:5.${L5_VER}.*" --no-update -v
- composer require "orchestra/testbench:3.${L5_VER}.*" --no-update -v
install: composer install --no-interaction
notifications:
  email: false
  slack:
    secure:  "m2RIkE0EmCgCnkvC+dr3svLiE1hxsTNhyDwxQmSTK9lClt1nqBcPCTjwA4o1keExkJB/OGKWZiRc3eqAwKL47nZsvy/HiqHOftMH5ch+kYxhpVnNl/SL2cGL7iDnWOhG6mP7qAqUp8uF63tdmArMbbSBvFJFuEKuuhbwKNfWb2T8oa/ZZjFGgbppYq2nQRbi1CvAV+d+1jAMZdwyzDN0yfpN451PtArCzYPHtR1wVAL5o/bfKCc6uVbiaPx1rzuqxRXqSmrfIyGWOqKaD+JX/VIf96XucJuRCpLOjXU/SE61Q9VAz8PguLkd9k3WVFPIjQhg+yzWtShQ0YebmbnDp8yC+WyemPseSRV+g2trH08Ks+/RHEdLiban3ttlQ+cdlDqYRz+tNVnYWrMykoRwY4sfPfTEy1/Hv29RpxEVSYvgOCPTrMkCTz0nKP2g2mpcA4lNU54ciOamWtJTNqGhn1HxNBx0YoSI0oU328X14IUHhyPWhtHWqTjvi1xZVypp8i39OC6EUYcWD+mVP4Off0rkCXQ3uuP6JOYe/y2lwK7NXh5+ELg6Rn9W7V9EtoXyLUWo5NA5pdS2xEyEVH8KjF14s5kErjDwXMpCmwXZI36oO1WfY4JIPm/CwYNhD0bFawIxcC4oOFZJVFbJ52Yf6qFh9M3TV++3d37clQNs1F8="
