language: php
cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '7.3'
  - '7.4'

env:
  - LARAVEL=6.0
  - LARAVEL=6.18
  - LARAVEL=6.18 TEST_DB_ENGINE=mysql
  - LARAVEL=6.18 TEST_DB_ENGINE=pgsql
  - LARAVEL=7.0
  - LARAVEL=7.28
  - LARAVEL=7.28 TEST_DB_ENGINE=mysql
  - LARAVEL=7.28 TEST_DB_ENGINE=pgsql
  - LARAVEL=8.0
  - LARAVEL=8.9
  - LARAVEL=8.9 TEST_DB_ENGINE=mysql
  - LARAVEL=8.9 TEST_DB_ENGINE=pgsql


script:
  - vendor/bin/phpunit --testdox
before_install:
  - MINOR=`echo $LARAVEL | sed 's/[6|7|8]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^7\.[0-9]+$ ]] && MAJOR=7 || MAJOR=6'
  - '[[ $LARAVEL =~ ^8\.[0-9]+$ ]] && MAJOR=8 || true'
  - echo "Testing against Laravel ${MAJOR}.${MINOR}"
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v
  - sh -c "[ ! -z $TEST_DB_ENGINE ] && [ 'mysql' = $TEST_DB_ENGINE ] && mysql -e 'DROP DATABASE IF EXISTS address_test;CREATE DATABASE address_test;'" || true
  - sh -c "[ ! -z $TEST_DB_ENGINE ] && [ 'pgsql' = $TEST_DB_ENGINE ] && psql -c 'create database address_test;' -U postgres" || true
install: composer install --no-interaction
services:
  - mysql
  - postgresql
notifications:
  email: false
  slack:
    secure:  "m2RIkE0EmCgCnkvC+dr3svLiE1hxsTNhyDwxQmSTK9lClt1nqBcPCTjwA4o1keExkJB/OGKWZiRc3eqAwKL47nZsvy/HiqHOftMH5ch+kYxhpVnNl/SL2cGL7iDnWOhG6mP7qAqUp8uF63tdmArMbbSBvFJFuEKuuhbwKNfWb2T8oa/ZZjFGgbppYq2nQRbi1CvAV+d+1jAMZdwyzDN0yfpN451PtArCzYPHtR1wVAL5o/bfKCc6uVbiaPx1rzuqxRXqSmrfIyGWOqKaD+JX/VIf96XucJuRCpLOjXU/SE61Q9VAz8PguLkd9k3WVFPIjQhg+yzWtShQ0YebmbnDp8yC+WyemPseSRV+g2trH08Ks+/RHEdLiban3ttlQ+cdlDqYRz+tNVnYWrMykoRwY4sfPfTEy1/Hv29RpxEVSYvgOCPTrMkCTz0nKP2g2mpcA4lNU54ciOamWtJTNqGhn1HxNBx0YoSI0oU328X14IUHhyPWhtHWqTjvi1xZVypp8i39OC6EUYcWD+mVP4Off0rkCXQ3uuP6JOYe/y2lwK7NXh5+ELg6Rn9W7V9EtoXyLUWo5NA5pdS2xEyEVH8KjF14s5kErjDwXMpCmwXZI36oO1WfY4JIPm/CwYNhD0bFawIxcC4oOFZJVFbJ52Yf6qFh9M3TV++3d37clQNs1F8="
