name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4']
        laravel: ['10.0', '10.48', '11.0', '11.14']
    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, sqlite3
          tools: composer:v2
      - name: Lock Package Versions
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}.*" --no-update -v
      - name: Prevent Laravel 10 + Doctrine 4
        run: |
          is_smaller_version() [[ $(echo -e "$1\n$2"|sort -V|head -1) != $2 ]]
          is_smaller_version "${{ matrix.laravel }}" "10.39" && composer req "doctrine/dbal:^3.5.1" --no-update || true
      - name: Composer Install
        run: composer install --prefer-dist --no-progress --no-interaction
      - name: Create SQLite Database
        run: mkdir -p database && touch database/database.sqlite
      - name: Run Tests [sqlite]
        run: php vendor/bin/phpunit --testdox
        env:
          TEST_DB_ENGINE: sqlite
      - name: Run Tests [mysql 5.7]
        run: php vendor/bin/phpunit --testdox
        env:
          TEST_DB_ENGINE: mysql
          TEST_DB_PORT: ${{ job.services.mysql.ports[3306] }}
      - name: Run Tests [mysql 8.0]
        run: php vendor/bin/phpunit --testdox
        env:
          TEST_DB_ENGINE: mysql
          TEST_DB_PORT: ${{ job.services.mysql8.ports[3306] }}
      - name: Run Tests [postgres]
        run: php vendor/bin/phpunit --testdox
        env:
          TEST_DB_ENGINE: pgsql
          TEST_DB_PORT: ${{ job.services.postgres.ports[5432] }}
          TEST_DB_PASSWORD: postgres
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: address_test
        ports:
          - 3306
      mysql8:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: address_test
        ports:
          - 3306
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: address_test
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
